name: Bug report
description: Report a bug
title: "[Bug]: "
labels:
  - bug
assignees:
  - SFM61319
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please tell us what happened in detail.
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: textarea
    id: what-should-have-happened
    attributes:
      label: What should have happened?
      description: Please tell us what should have happened instead, and why.
      placeholder: Tell us what you think you should see!
      value: The bug should not have happened!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How do we reproduce this bug?
      description: Please tell us how one can reproduce this bug, step-by-step if possible.
      placeholder: Tell us how to see what you saw!
      value: "The following is a step-by-step process to reproduce this bug:"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Since what version of `ds` have you been seeing this problem?
      multiple: false
      options:
        - 0.8.0
        - 0.7.0
        - 0.6.0
        - 0.5.0
        - 0.4.0
        - 0.3.0
        - 0.2.0
        - 0.1.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What operating systems are you seeing this problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: Architectures
      description: What architectures are you seeing this problem on?
      multiple: true
      options:
        - 32-bit
        - 64-bit
    validations:
      required: true
